services:
  - type: web
    name: zenith-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://zenith-backend-xevt.onrender.com/api/v1
      - key: VITE_ML_API_URL
        value: https://zenith-ml-engine.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
